### PR TITLE
fixed strict standards warning 

### PR DESCRIPTION
**Pull request by ghost**
Hello,
This is a tiny fix to get rid of PHP strict standard warnings when loading de doc for a module
The warning is: 'Only variables should be passed by reference', at lines 753 and 950 of lib/generate.php

### CODE REVIEW

**Comment by wkeese** [comment]
Thanks for the patch.   I'm confused though.   The main change you are making is:

```
-  $prop = array_pop(explode(".", $page));
+  $prop = substr(strrchr($page, '.'), 1);
```

How does that get rid of strict warnings, and what does it have to do with passing variables by reference?

**Comment by geonef** [comment]
Yes, it's tiny indeed! ;)

array_pop() asks for a reference, although explode() would of course give a value.

The fix not only fixes the warning, but also does it the "right" way, since in the code you just need the string after the last "." (explode+pop is heavy but useless for such a simple need)

**Comment by wkeese** [comment]
I see.   Hmm but what if there are no dots in the $page string.    Admittedly, that will likely never happen but...

**Comment by geonef** [comment]
It should be okay. If $page has no dots, strrchr() returns FALSE and so does substr() when its first arg is FALSE.

So it is FALSE instead of NULL when array_pop() was used.

**Comment by wkeese** [comment]
I thought that explode(".", "__Foo") would return an array with one element ["__Foo"], and thus that  array_pop(explode(".", "_Foo")) would return "__Foo", not NULL or FALSE.

**Comment by geonef** [comment]
Indeed, you are right about explode().

To handle the no-dot value, I would write :  $prop = substr(strrchr($page, '.'), 1) ?: $page;

But if you prefer to stick to explode(), you just have to use a temp variable for use by array_pop(), that it could take as a reference:

$exploded = explode(".", $page);
$prop = array_pop($exploded);

**Comment by wkeese** [comment]
Wow I don't know that ?: syntax.    Maybe the best solution is to just use a regex to trim everything up to and including the last dot, like preg_replace(".*\\.", "", $page)?

**Comment by geonef** [comment]
Yes, a preg_match() is probably better, and more concise.

The "X ?: Y" operator is equivalent to "X ? X : Y" and is available on PHP
5.3+.

**Comment by wkeese** [comment]
Got it.   OK I'll check in your patch first, and then make that additional change so that it can handle a theoretical $page of dijit/__FooConstraints in addition to the typical dijit/form/DateTextBox.__Constraints.

**Comment by wkeese** [comment]
My additional change: 503f1d7e4d52013ad33a09538950085f7a3b21b0

**Comment by geonef** [comment]
Thanks!

**Comment by wkeese** [comment]
BTW, explode() is used in lots of other places in the viewer, so I'm surprised there's no where else generating strict warnings.

**Comment by geonef** [comment]
Actually, I did not have strict warning reporting enabled all the time, so
I can't be sure there are no other warnings.

I juste searched for occurences of explode(), indeed they are many, but the
only suspect form I have found is array_pop(explode(...))

lib/item.php:45
lib/item.php:53
lib/item.php:62
rpc/index.php:171
rpc/index.php:171
rpc/index.php:179
rpc/index.php:188

**Pull request merged**
