### PR TITLE
Basic clean-up of API landing page

### PR DESCRIPTION
**Pull request by dylans**
Hide references to dojo, dijit, and dojox links for 1.8 API viewer landing page, and update link to how to create your own docs based on version.

Note, this needs to be tested, as I wrote this diff within GitHub.

### CODE REVIEW

**Comment by wkeese** [comment]
OK, well currently looks like we are using the dtk theme, not the dtk_prd one, so changing dtk_prd won't help.

**Comment by wkeese** [comment]
The other thing is that dijit/form, dijit/layout, and dojox/grid are also invalid because none of those things are modules.

**Comment by dylans** [comment]
Ok, I'll try something different tonight or tomorrow (will reorganize the correct file with something that will just highlight popular or commonly used APIs)

**Comment by wkeese** [comment]
No, I already fixed it.

**Pull request closed without merging**
